name: My Wordpress site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }}
      - run: git clone git@github.com:WordPress/WordPress.git
      - run: ls ${{ github.workspace }}